/**
 * GPX-Mapping für "Guck ma, Westerwald" PWA
 * Generiert: 2026-05-17
 *
 * Schlüssel-Format: "<typ>:<gruppe>:<idx>"
 * Wert: { dateiname, titel }
 *
 * Verwendung in app.js: findeGpxDateinameLokal(typ, gruppe, idx)
 */
var GPX_MAPPING = {
  'wandern:westerwaldsteig:0': { dateiname: 'westerwaldsteig-01-herborn-breitscheid-ost-west.gpx', titel: 'WesterwaldSteig 01. Etappe Herborn – Breitscheid (Ost-West)' },
  'wandern:westerwaldsteig:1': { dateiname: 'westerwaldsteig-02-breitscheid-rehe-ost-west.gpx', titel: 'WesterwaldSteig 02. Etappe Breitscheid – Rehe (Ost-West)' },
  'wandern:westerwaldsteig:2': { dateiname: 'westerwaldsteig-03-rehe-rennerod-ost-west.gpx', titel: 'WesterwaldSteig 03. Etappe Rehe – Rennerod (Ost-West)' },
  'wandern:westerwaldsteig:3': { dateiname: 'westerwaldsteig-04-rennerod-westerburg-ost-west.gpx', titel: 'WesterwaldSteig 04. Etappe Rennerod – Westerburg (Ost-West)' },
  'wandern:westerwaldsteig:4': { dateiname: 'westerwaldsteig-05-westerburg-freilingen-ost-wes.gpx', titel: 'WesterwaldSteig 05. Etappe Westerburg – Freilingen (Ost-West)' },
  'wandern:westerwaldsteig:5': { dateiname: 'westerwaldsteig-06-freilingen-nistertal-ost-west.gpx', titel: 'WesterwaldSteig 06. Etappe Freilingen – Nistertal (Ost-West)' },
  'wandern:westerwaldsteig:6': { dateiname: 'westerwaldsteig-07-nistertal-bad-marienberg-ost.gpx', titel: 'WesterwaldSteig 07. Etappe Nistertal – Bad Marienberg (Ost-West)' },
  'wandern:westerwaldsteig:7': { dateiname: 'westerwaldsteig-08-bad-marienberg-hachenburg-ost.gpx', titel: 'WesterwaldSteig 08. Etappe Bad Marienberg – Hachenburg (Ost-West)' },
  'wandern:westerwaldsteig:8': { dateiname: 'westerwaldsteig-09-hachenburg-limbach-ost-west.gpx', titel: 'WesterwaldSteig 09. Etappe Hachenburg – Limbach (Ost-West)' },
  'wandern:westerwaldsteig:9': { dateiname: 'westerwaldsteig-10-limbach-kloster-marienthal-os.gpx', titel: 'WesterwaldSteig 10. Etappe Limbach – Kloster Marienthal (Ost-West)' },
  'wandern:westerwaldsteig:10': { dateiname: 'westerwaldsteig-11-kloster-marienthal-weyerbusch.gpx', titel: 'WesterwaldSteig 11. Etappe Kloster Marienthal – Weyerbusch (Ost-West)' },
  'wandern:westerwaldsteig:11': { dateiname: 'westerwaldsteig-12-weyerbusch-flammersfeld-ost-w.gpx', titel: 'WesterwaldSteig 12. Etappe Weyerbusch – Flammersfeld (Ost-West)' },
  'wandern:westerwaldsteig:12': { dateiname: 'westerwaldsteig-13-flammersfeld-horhausen-ost-we.gpx', titel: 'WesterwaldSteig 13. Etappe Flammersfeld – Horhausen (Ost-West)' },
  'wandern:westerwaldsteig:13': { dateiname: 'westerwaldsteig-14-horhausen-strauscheid-ost-wes.gpx', titel: 'WesterwaldSteig 14. Etappe Horhausen – Strauscheid (Ost-West)' },
  'wandern:westerwaldsteig:14': { dateiname: 'westerwaldsteig-15-strauscheid-waldbreitbach-ost.gpx', titel: 'WesterwaldSteig 15. Etappe Strauscheid – Waldbreitbach (Ost-West)' },
  'wandern:westerwaldsteig:15': { dateiname: 'westerwaldsteig-16-waldbreitbach-bad-hoenningen.gpx', titel: 'WesterwaldSteig 16. Etappe Waldbreitbach – Bad Hönningen/Rheinbrohl (Ost-West)' },
  'wandern:druidensteig:0': { dateiname: 'druidensteig-01-freusburg-kirchen-sieg.gpx', titel: 'Druidensteig 01. Etappe Freusburg – Kirchen (Sieg)' },
  'wandern:druidensteig:1': { dateiname: 'druidensteig-02-kirchen-sieg-herdorf-sassenroth.gpx', titel: 'Druidensteig 02. Etappe Kirchen (Sieg) – Herdorf-Sassenroth' },
  'wandern:druidensteig:2': { dateiname: 'druidensteig-03-herdorf-sassenroth-daaden.gpx', titel: 'Druidensteig 03. Etappe Herdorf-Sassenroth – Daaden' },
  'wandern:druidensteig:3': { dateiname: 'druidensteig-04-daaden-elkenrother-weiher.gpx', titel: 'Druidensteig 04. Etappe Daaden – Elkenrother Weiher' },
  'wandern:druidensteig:4': { dateiname: 'druidensteig-05-elkenrother-weiher-betzdorf.gpx', titel: 'Druidensteig 05. Etappe Elkenrother Weiher – Betzdorf' },
  'wandern:druidensteig:5': { dateiname: 'druidensteig-06-betzdorf-steinebach.gpx', titel: 'Druidensteig 06. Etappe Betzdorf – Steinebach' },
  'wandern:druidensteig:6': { dateiname: 'druidensteig-07-grube-bindweide-hachenburg.gpx', titel: 'Druidensteig 07. Etappe Grube Bindweide – Hachenburg' },
  'wandern:wiedweg:0': { dateiname: 'wiedweg-01-hachenburg-linden.gpx', titel: 'Wiedweg 01. Etappe Hachenburg – Linden' },
  'wandern:wiedweg:1': { dateiname: 'wiedweg-02-linden-hoechstenbach.gpx', titel: 'Wiedweg 02. Etappe Linden – Höchstenbach' },
  'wandern:wiedweg:2': { dateiname: 'wiedweg-03-hoechstenbach-altenkirchen.gpx', titel: 'Wiedweg 03. Etappe Höchstenbach – Altenkirchen' },
  'wandern:wiedweg:3': { dateiname: 'wiedweg-04-altenkirchen-oberlahr.gpx', titel: 'Wiedweg 04. Etappe Altenkirchen – Oberlahr' },
  'wandern:wiedweg:4': { dateiname: 'wiedweg-05-oberlahr-neustadt-wied.gpx', titel: 'Wiedweg 05. Etappe Oberlahr – Neustadt (Wied)' },
  'wandern:wiedweg:5': { dateiname: 'wiedweg-06-neustadt-wied-rossbach-wied.gpx', titel: 'Wiedweg 06. Etappe Neustadt (Wied) – Roßbach/Wied' },
  'wandern:wiedweg:6': { dateiname: 'wiedweg-07-rossbach-wied-niederbreitbach.gpx', titel: 'Wiedweg 07. Etappe Roßbach/Wied – Niederbreitbach' },
  'wandern:wiedweg:7': { dateiname: 'wiedweg-08-niederbreitbach-irlich-neuwied.gpx', titel: 'Wiedweg 08. Etappe Niederbreitbach – Irlich (Neuwied)' },
  'wandern:wiedweg:8': { dateiname: 'wiedweg-09-gesamtstrecke.gpx', titel: 'Wiedweg Gesamtstrecke' },
  'wandern:kleine-waeller:0': { dateiname: 'kleine-waeller-01-r-waeller-haeubchen-tour.gpx', titel: 'Kleiner Wäller Häubchen-Tour' },
  'wandern:kleine-waeller:1': { dateiname: 'kleine-waeller-02-r-waeller-wied-runde.gpx', titel: 'Kleiner Wäller Wied-Runde' },
  'wandern:kleine-waeller:2': { dateiname: 'kleine-waeller-03-r-waeller-malbergseeblick.gpx', titel: 'Kleiner Wäller MalbergSeeBlick' },
  'wandern:kleine-waeller:3': { dateiname: 'kleine-waeller-04-r-waeller-zwergenweg-2.gpx', titel: 'Kleiner Wäller Zwergenweg 2' },
  'wandern:kleine-waeller:4': { dateiname: 'kleine-waeller-05-r-waeller-loewenspur-1-orange.gpx', titel: 'Kleiner Wäller Löwenspur 1 (orange)' },
  'wandern:kleine-waeller:5': { dateiname: 'kleine-waeller-06-r-waeller-loewenspur-2-rot.gpx', titel: 'Kleiner Wäller Löwenspur 2 (rot)' },
  'wandern:kleine-waeller:6': { dateiname: 'kleine-waeller-07-r-waeller-loewenspur-3-blau.gpx', titel: 'Kleiner Wäller Löwenspur 3 (blau)' },
  'wandern:kleine-waeller:7': { dateiname: 'kleine-waeller-08-r-waeller-basalt-wasser.gpx', titel: 'Kleiner Wäller Basalt + Wasser' },
  'wandern:kleine-waeller:8': { dateiname: 'kleine-waeller-09-r-waeller-sagenweg.gpx', titel: 'Kleiner Wäller Sagenweg' },
  'wandern:kleine-waeller:9': { dateiname: 'kleine-waeller-10-r-waeller-klangpfad.gpx', titel: 'Kleiner Wäller Klangpfad' },
  'wandern:kleine-waeller:10': { dateiname: 'kleine-waeller-11-r-waeller-kunst-natur.gpx', titel: 'Kleiner Wäller Kunst + Natur' },
  'wandern:kleine-waeller:11': { dateiname: 'kleine-waeller-12-r-waeller-wolfsteine.gpx', titel: 'Kleiner Wäller Wolfsteine' },
  'wandern:kleine-waeller:12': { dateiname: 'kleine-waeller-13-r-waeller-weg-der-sinne.gpx', titel: 'Kleiner Wäller Weg der Sinne' },
  'wandern:kleine-waeller:13': { dateiname: 'kleine-waeller-14-r-waeller-vitalparcours.gpx', titel: 'Kleiner Wäller Vitalparcours' },
  'wandern:kleine-waeller:14': { dateiname: 'kleine-waeller-15-r-waeller-und-georoute-glasstadt-wirges.gpx', titel: 'Kleiner Wäller und GeoRoute Glasstadt Wirges' },
  'wandern:kleine-waeller:15': { dateiname: 'kleine-waeller-16-r-waeller-schwarze-nister-bad-marienberg.gpx', titel: 'Kleiner Wäller Schwarze Nister - Bad Marienberg' },
  'wandern:kleine-waeller:16': { dateiname: 'kleine-waeller-17-r-waeller-wiesensee-stahlhofen-am-wiesensee.gpx', titel: 'Kleiner Wäller Wiesensee - Stahlhofen am Wiesensee' },
  'wandern:kleine-waeller:17': { dateiname: 'kleine-waeller-18-r-waeller-westerburg.gpx', titel: 'Kleiner Wäller Westerburg' },
  'wandern:kleine-waeller:18': { dateiname: 'kleine-waeller-19-r-waeller-rund-um-mabuehl-oberroder-knoten.gpx', titel: 'Kleiner Wäller Rund um Mabühl - Oberroder Knoten' },
  'wandern:kleine-waeller:19': { dateiname: 'kleine-waeller-20-r-waeller-hessentagswanderweg-herborn.gpx', titel: 'Kleiner Wäller Hessentagswanderweg - Herborn' },
  'wandern:waeller-touren:0': { dateiname: 'waeller-touren-01-stoeffel-route-stockum-pueschen-enspel.gpx', titel: 'Wäller Tour Stöffel-Route - Stockum-Püschen / Enspel' },
  'wandern:waeller-touren:1': { dateiname: 'waeller-touren-02-vom-teufelsberg-zur-caaner-schweiz-nauort.gpx', titel: 'Wäller Tour Vom Teufelsberg zur Caaner Schweiz - Nauort' },
  'wandern:waeller-touren:2': { dateiname: 'waeller-touren-03-basalt-und-buntmetalle-neustadt-wied.gpx', titel: 'Wäller Tour Basalt und Buntmetalle - Neustadt (Wied)' },
  'wandern:waeller-touren:3': { dateiname: 'waeller-touren-04-baerenkopp-waldbreitbach.gpx', titel: 'Wäller Tour Bärenkopp - Waldbreitbach' },
  'wandern:waeller-touren:4': { dateiname: 'waeller-touren-05-klosterweg-rengsdorf-waldbreitbach.gpx', titel: 'Wäller Tour Klosterweg - Rengsdorf/Waldbreitbach' },
  'wandern:waeller-touren:5': { dateiname: 'waeller-touren-06-iserbachschleife-anhausen.gpx', titel: 'Wäller Tour Iserbachschleife - Anhausen' },
  'wandern:waeller-touren:6': { dateiname: 'waeller-touren-07-brexbachschluchtweg-grenzau.gpx', titel: 'Wäller Tour Brexbachschluchtweg - Grenzau' },
  'wandern:waeller-touren:7': { dateiname: 'waeller-touren-08-augst-neuhaeusel.gpx', titel: 'Wäller Tour Augst - Neuhäusel' },
  'wandern:waeller-touren:8': { dateiname: 'waeller-touren-09-elberthoehen-niederelbert.gpx', titel: 'Wäller Tour Elberthöhen - Niederelbert' },
  'wandern:waeller-touren:9': { dateiname: 'waeller-touren-10-buchfinkenland-gackenbach.gpx', titel: 'Wäller Tour Buchfinkenland - Gackenbach' },
  'wandern:waeller-touren:10': { dateiname: 'waeller-touren-11-eisenbachtal-nomborn.gpx', titel: 'Wäller Tour Eisenbachtal - Nomborn' },
  'wandern:waeller-touren:11': { dateiname: 'waeller-touren-12-watzenhahner-riesen-weltersburg.gpx', titel: 'Wäller Tour Watzenhahner Riesen - Weltersburg' },
  'wandern:waeller-touren:12': { dateiname: 'waeller-touren-13-hohe-hahnscheid-irmtraut.gpx', titel: 'Wäller Tour Hohe Hahnscheid - Irmtraut' },
  'wandern:waeller-touren:13': { dateiname: 'waeller-touren-14-greifenstein-schleife-etappe-1-herborn-beilstein.gpx', titel: 'Wäller Tour Greifenstein-Schleife - Etappe 1 - Herborn/Beilstein' },
  'wandern:waeller-touren:14': { dateiname: 'waeller-touren-15-greifenstein-schleife-etappe-2-beilstein-krombachtalsperre.gpx', titel: 'Wäller Tour Greifenstein-Schleife - Etappe 2 - Beilstein/Krombachtalsperre' },
  'wandern:waeller-touren:15': { dateiname: 'waeller-touren-16-greifenstein-schleife-gesamt-herborn.gpx', titel: 'Wäller Tour Greifenstein-Schleife - gesamt - Herborn' },
  'wandern:waeller-touren:16': { dateiname: 'waeller-touren-17-bachgefluester-marienstatt.gpx', titel: 'Wäller Tour Bachgeflüster - Marienstatt' },
  'wandern:waeller-touren:17': { dateiname: 'waeller-touren-18-grubenwanderweg-brachbach.gpx', titel: 'Wäller Tour Grubenwanderweg Brachbach' },
  'wandern:waeller-touren:18': { dateiname: 'waeller-touren-19-druidenstein-wanderweg-kirchen-sieg.gpx', titel: 'Wäller Tour Druidenstein-Wanderweg - Kirchen (Sieg)' },
  'wandern:waeller-touren:19': { dateiname: 'waeller-touren-20-raiffeisens-sonntagsspaziergang-hamm-sieg.gpx', titel: 'Wäller Tour Raiffeisens Sonntagsspaziergang - Hamm (Sieg)' },
  'rad:rundradwege:0': { dateiname: 'rundradwege-01-altenkirchener-radrundweg-tallandschaften-um-altenkirch.gpx', titel: 'Altenkirchener Radrundweg - Tallandschaften um Altenkirchen' },
  'rad:rundradwege:1': { dateiname: 'rundradwege-02-baeche-tour-xiii-erkunde-die-landschaft-zwischen-brexba.gpx', titel: 'Bäche-Tour (XIII): Erkunde die Landschaft zwischen Brexbach und Saynbach' },
  'rad:rundradwege:2': { dateiname: 'rundradwege-03-kannenbaeckerland-route-abwechslung-zwischen-toepfereie.gpx', titel: 'Kannenbäckerland-Route: Abwechslung zwischen Töpfereien, Westerwälder Dom und Erlenhofsee' },
  'rad:rundradwege:3': { dateiname: 'rundradwege-04-viel-erleben-auf-dem-radrundweg-seenplatte-i.gpx', titel: 'Viel erleben auf dem Radrundweg Seenplatte (I)' },
  'rad:rundradwege:4': { dateiname: 'rundradwege-05-nister-wiesensee-tour-eine-grosse-rundfahrt-um-den-wies.gpx', titel: 'Nister-Wiesensee-Tour: eine große Rundfahrt um den Wiesensee' },
  'rad:rundradwege:5': { dateiname: 'rundradwege-06-rund-um-den-knoten-malerische-fahrt-durch-typische-land.gpx', titel: 'Rund um den Knoten: malerische Fahrt durch typische Landschaften' },
  'rad:rundradwege:6': { dateiname: 'rundradwege-07-hoeferadeln-ab-flammersfeld.gpx', titel: 'Höferadeln ab Flammersfeld' },
  'rad:rundradwege:7': { dateiname: 'rundradwege-08-5-seen-radweg-natur-und-wasser-erleben.gpx', titel: '5-Seen Radweg: Natur und Wasser erleben' },
  'rad:rundradwege:8': { dateiname: 'rundradwege-09-anspruchsvoll-und-kurzweilig-unterwegs-auf-dem-rundradw.gpx', titel: 'Anspruchsvoll und kurzweilig: unterwegs auf dem Rundradweg WW1' },
  'rad:rundradwege:9': { dateiname: 'rundradwege-10-hachenburger-westerwald-abwechslungsreiche-rundtour.gpx', titel: 'Hachenburger Westerwald: Abwechslungsreiche Rundtour' },
  'rad:rundradwege:10': { dateiname: 'rundradwege-11-helmenzen-ak-radtour-5-von-tal-zu-tal.gpx', titel: 'Helmenzen - AK-Radtour 5 "Von Tal zu Tal"' },
  'rad:rundradwege:11': { dateiname: 'rundradwege-12-mammelzen-ak-radtour-8-die-kleine-tour.gpx', titel: 'Mammelzen - AK-Radtour 8 "Die kleine Tour"' },
  'rad:rundradwege:12': { dateiname: 'rundradwege-13-die-backesdoerfer-tour-genussvolles-radfahren-zwischen.gpx', titel: 'Die Backesdörfer-Tour: Genussvolles Radfahren zwischen Wallmerod und Westerburg' },
  'rad:rundradwege:13': { dateiname: 'rundradwege-14-bad-marienberg-tour-abenteuer-fuer-fortgeschrittene.gpx', titel: 'Bad Marienberg-Tour: Abenteuer für Fortgeschrittene' },
  'rad:rundradwege:14': { dateiname: 'rundradwege-15-saynbachroute-aus-dem-saynbachtal-hinauf-zum-woelferlin.gpx', titel: 'Saynbachroute: aus dem Saynbachtal hinauf zum Wölferlinger Kopf' },
  'rad:rundradwege:15': { dateiname: 'rundradwege-16-radrundtour-puderbacher-land-eine-fahrt-mit-hoehen-und.gpx', titel: 'Radrundtour Puderbacher Land: eine Fahrt mit Höhen und Tiefen' },
  'rad:rundradwege:16': { dateiname: 'rundradwege-17-hohlwege-um-altenkirchen-mit-dem-rad-entdecken.gpx', titel: 'Hohlwege um Altenkirchen mit dem Rad entdecken' },
  'rad:rundradwege:17': { dateiname: 'rundradwege-18-weyerbusch-ak-radtour-2-wassergrenze-zwischen-wied-und.gpx', titel: 'Weyerbusch - AK-Radtour 2 "Wassergrenze zwischen Wied und Sieg"' },
  'rad:rundradwege:18': { dateiname: 'rundradwege-19-ahround-tour-ii-entdecke-malerische-doerfer-auf-einer-k.gpx', titel: 'AHRound-Tour (II): Entdecke malerische Dörfer auf einer kleinen Runde' },
  'rad:rundradwege:19': { dateiname: 'rundradwege-20-hilkhausen-ak-radtour-3-zwischen-birnbach-und-mehrbacht.gpx', titel: 'Hilkhausen - AK-Radtour 3 "Zwischen Birnbach- und Mehrbachtal"' },
  'rad:rundradwege:20': { dateiname: 'rundradwege-21-aubach-tour-xvii-schoene-rundtour-fuer-einen-entspannte.gpx', titel: 'Aubach-Tour (XVII): Schöne Rundtour für einen entspannten Nachmittag' },
  'rad:rundradwege:21': { dateiname: 'rundradwege-22-kircheib-ak-radtour-1-kirchen-und-andere-altertuemer.gpx', titel: 'Kircheib - AK-Radtour 1 "Kirchen und andere Altertümer"' },
  'rad:rundradwege:22': { dateiname: 'rundradwege-23-oberwambach-ak-radtour-7-herzberg-oder-harzburg.gpx', titel: 'Oberwambach - AK-Radtour 7 "Herzberg oder Harzburg"' },
  'rad:rundradwege:23': { dateiname: 'rundradwege-24-koeppel-route-unterwegs-im-kannenbaeckerland-zwischen-h.gpx', titel: 'Köppel-Route: Unterwegs im Kannenbäckerland zwischen Höhr-Grenzhausen und Montabaur' },
  'rad:rundradwege:24': { dateiname: 'rundradwege-25-stoeffelmaus-tour-rund-um-die-stoeffelmaus-unterwegs-in.gpx', titel: 'Stöffelmaus-Tour: Rund um die Stöffelmaus unterwegs in wunderbaren Landschaften' },
  'rad:rundradwege:25': { dateiname: 'rundradwege-26-bahntrassen-tour-von-bad-marienberg-ins-schoene-nistert.gpx', titel: 'Bahntrassen-Tour: von Bad Marienberg ins schöne Nistertal' },
  'rad:rundradwege:26': { dateiname: 'rundradwege-27-altenkirchen-ak-radtour-4-blick-ueber-altenkirchen.gpx', titel: 'Altenkirchen - AK-Radtour 4 "Blick über Altenkirchen"' },
  'rad:rundradwege:27': { dateiname: 'rundradwege-28-waellerland-manoever-in-reizvollen-schleifen-durch-das.gpx', titel: 'WällerLand-Manöver: In reizvollen Schleifen durch das Wäller Land' },
  'rad:rundradwege:28': { dateiname: 'rundradwege-29-fuchskauten-tour.gpx', titel: 'Fuchskauten Tour' },
  'rad:rundradwege:29': { dateiname: 'rundradwege-30-buchfinken-gelbach-tour-xii-bezaubernde-region-zwischen.gpx', titel: 'Buchfinken-Gelbach-Tour (XII): bezaubernde Region zwischen Buchfinkenlandschaft und Gelbachtal' },
  'rad:rundradwege:30': { dateiname: 'rundradwege-31-hilgenroth-ak-radtour-6-am-hoechsten-punkt.gpx', titel: 'Hilgenroth - AK-Radtour 6 "Am höchsten Punkt"' },
  'rad:rundradwege:31': { dateiname: 'rundradwege-32-kleine-nister-tour-waldreiche-tour-und-malerische-orte.gpx', titel: 'Kleine Nister-Tour: Waldreiche Tour und malerische Orte im Gebiet der Kleinen Nister' },
  'rad:rundradwege:32': { dateiname: 'rundradwege-33-raiffeisen-runde.gpx', titel: 'Raiffeisen-Runde' },
  'rad:rundradwege:33': { dateiname: 'rundradwege-34-hoeferadeln-ab-altenkirchen-westerwald.gpx', titel: 'Höferadeln ab Altenkirchen (Westerwald)' },
  'rad:rundradwege:34': { dateiname: 'rundradwege-35-familien-radtour-in-der-verbandsgemeinde-asbach.gpx', titel: 'Familien-Radtour in der Verbandsgemeinde Asbach' },
  'rad:rundradwege:35': { dateiname: 'rundradwege-36-mit-dem-bike-durch-licht-und-schatten-rund-um-selters.gpx', titel: 'Mit dem Bike durch "Licht und Schatten rund um Selters"' },
  'rad:streckenradwege:0': { dateiname: 'streckenradwege-01-auf-dem-wied-radweg-durch-herrliche-flusstaeler-radeln.gpx', titel: 'Auf dem Wied-Radweg durch herrliche Flusstäler radeln' },
  'rad:streckenradwege:1': { dateiname: 'streckenradwege-02-nister-radweg-eine-reizvolle-tour-von-der-quelle-bis-zu.gpx', titel: 'Nister-Radweg: eine reizvolle Tour von der Quelle bis zur Mündung' },
  'rad:streckenradwege:2': { dateiname: 'streckenradwege-03-radtour-suedlicher-westerwald-eine-schoene-fahrt-fuer-a.gpx', titel: 'Radtour Südlicher Westerwald: eine schöne Fahrt für Anspruchsvolle' },
  'rad:streckenradwege:3': { dateiname: 'streckenradwege-04-auf-der-westerwaldschleife-in-vier-etappen-durch-die-re.gpx', titel: 'Auf der Westerwaldschleife in vier Etappen durch die Region' },
  'rad:streckenradwege:4': { dateiname: 'streckenradwege-05-westerwaldschleife-linz-rhein-wissen-sieg.gpx', titel: 'Westerwaldschleife: Linz/Rhein - Wissen/Sieg' },
  'rad:streckenradwege:5': { dateiname: 'streckenradwege-06-westerwaldschleife-wissen-daaden.gpx', titel: 'Westerwaldschleife: Wissen - Daaden' },
  'rad:streckenradwege:6': { dateiname: 'streckenradwege-07-westerwaldschleife-daaden-wiesensee.gpx', titel: 'Westerwaldschleife: Daaden - Wiesensee' },
  'rad:streckenradwege:7': { dateiname: 'streckenradwege-08-westerwaldschleife-wiesensee-diez.gpx', titel: 'Westerwaldschleife: Wiesensee - Diez' },
  'rad:streckenradwege:8': { dateiname: 'streckenradwege-09-anspruchsvoll-und-kurzweilig-unterwegs-auf-dem-rundradw.gpx', titel: 'Anspruchsvoll und kurzweilig: unterwegs auf dem Rundradweg WW1' },
  'rad:streckenradwege:9': { dateiname: 'streckenradwege-10-ww1-fuchskaute-hachenburg.gpx', titel: 'WW1: Fuchskaute - Hachenburg' },
  'rad:streckenradwege:10': { dateiname: 'streckenradwege-11-ww1-grenzau-nomborn.gpx', titel: 'WW1: Grenzau - Nomborn' },
  'rad:streckenradwege:11': { dateiname: 'streckenradwege-12-ww1-nomborn-fuchskaute.gpx', titel: 'WW1: Nomborn - Fuchskaute' },
  'rad:streckenradwege:12': { dateiname: 'streckenradwege-13-ww1-hachenburg-grenzau.gpx', titel: 'WW1: Hachenburg - Grenzau' },
  'rad:streckenradwege:13': { dateiname: 'streckenradwege-14-ruhr-sieg-radweg.gpx', titel: 'Ruhr-Sieg-Radweg' },
  'rad:streckenradwege:14': { dateiname: 'streckenradwege-15-mit-dem-westerwald-lahn-radweg-einmal-quer-durch-die-re.gpx', titel: 'Mit dem Westerwald-Lahn-Radweg einmal quer durch die Region' },
  'rad:streckenradwege:15': { dateiname: 'streckenradwege-16-westerwald-rhein-radweg-von-der-kirchlinde-bis-zum-lime.gpx', titel: 'Westerwald-Rhein-Radweg: von der Kirchlinde bis zum Limes' },
  'rad:gravelbike:0': { dateiname: 'gravelbike-01-hachenburger-westerwald-abwechslungsreiche-rundtour.gpx', titel: 'Hachenburger Westerwald: Abwechslungsreiche Rundtour' },
  'rad:gravelbike:1': { dateiname: 'gravelbike-02-bad-marienberg-tour-abenteuer-fuer-fortgeschrittene.gpx', titel: 'Bad Marienberg-Tour: Abenteuer für Fortgeschrittene' },
  'rad:gravelbike:2': { dateiname: 'gravelbike-03-kannenbaeckerland-route-abwechslung-zwischen-toepfereie.gpx', titel: 'Kannenbäckerland-Route: Abwechslung zwischen Töpfereien, Westerwälder Dom und Erlenhofsee' },
  'rad:gravelbike:3': { dateiname: 'gravelbike-04-fuchskauten-tour.gpx', titel: 'Fuchskauten Tour' },
  'rad:gravelbike:4': { dateiname: 'gravelbike-05-rund-um-den-knoten-malerische-fahrt-durch-typische-land.gpx', titel: 'Rund um den Knoten: malerische Fahrt durch typische Landschaften' },
  'rad:gravelbike:5': { dateiname: 'gravelbike-06-sechs-baeche-tour-gravel-emtb-wiedtal-westerwald.gpx', titel: 'Sechs-Bäche-Tour - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:gravelbike:6': { dateiname: 'gravelbike-07-schottern-durchs-rengsdorfer-land-gravel-emtb-wiedtal-w.gpx', titel: 'Schottern durchs Rengsdorfer Land - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:gravelbike:7': { dateiname: 'gravelbike-08-holy-gravel-gravel-emtb-wiedtal-westerwald.gpx', titel: 'Holy Gravel! - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:gravelbike:8': { dateiname: 'gravelbike-09-wiedheights-gravel-emtb-wiedtal-westerwald.gpx', titel: 'WiedHeights - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:mountainbike:0': { dateiname: 'mountainbike-01-hauptroute-a-sportliche-mountainbike-tour-mit-kleineren.gpx', titel: 'Hauptroute (A): sportliche Mountainbike-Tour mit kleineren sowie drei großen Anstiegen' },
  'rad:mountainbike:1': { dateiname: 'mountainbike-02-fuesseberg-runde-b-auf-der-einsteigertour-durch-den-noe.gpx', titel: 'Füsseberg-Runde (B): auf der Einsteigertour durch den Nördlichen Westerwald' },
  'rad:mountainbike:2': { dateiname: 'mountainbike-03-bergmannspfad-c-reizvolle-tour-mit-rund-100-metern-hoeh.gpx', titel: 'Bergmannspfad (C): reizvolle Tour mit rund 100 Metern Höhenunterschied' },
  'rad:mountainbike:3': { dateiname: 'mountainbike-04-galgenkopf-runde-d-sportliche-mountainbike-herausforder.gpx', titel: 'Galgenkopf-Runde (D): sportliche Mountainbike-Herausforderung im Tierschutzgebiet Westerwald' },
  'rad:mountainbike:4': { dateiname: 'mountainbike-05-scheuerberg-schleife-e-herausfordernde-mountainbike-tou.gpx', titel: 'Scheuerberg-Schleife (E): herausfordernde Mountainbike-Tour durch den Wald südwestlich von Betzdorf' },
  'rad:mountainbike:5': { dateiname: 'mountainbike-06-sechs-baeche-tour-gravel-emtb-wiedtal-westerwald.gpx', titel: 'Sechs-Bäche-Tour - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:mountainbike:6': { dateiname: 'mountainbike-07-schottern-durchs-rengsdorfer-land-gravel-emtb-wiedtal-w.gpx', titel: 'Schottern durchs Rengsdorfer Land - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:mountainbike:7': { dateiname: 'mountainbike-08-holy-gravel-gravel-emtb-wiedtal-westerwald.gpx', titel: 'Holy Gravel! - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:mountainbike:8': { dateiname: 'mountainbike-09-wiedheights-gravel-emtb-wiedtal-westerwald.gpx', titel: 'WiedHeights - Gravel & eMTB | Wiedtal-Westerwald' },
  'rad:rennrad:0': { dateiname: 'rennrad-01-westerwaelder-express-runde.gpx', titel: 'Westerwälder Express-Runde' },
  'rad:rennrad:1': { dateiname: 'rennrad-02-westerwaelder-seen-runde.gpx', titel: 'Westerwälder Seen-Runde' },
  'rad:rennrad:2': { dateiname: 'rennrad-03-westerwaelder-klassiker-runde.gpx', titel: 'Westerwälder Klassiker-Runde' },
  'rad:rennrad:3': { dateiname: 'rennrad-04-westerwaelder-feierabend-runde.gpx', titel: 'Westerwälder Feierabend-Runde' },
  'rad:rennrad:4': { dateiname: 'rennrad-05-westerwaelder-stadt-land-klosterrunde.gpx', titel: 'Westerwälder Stadt-Land-Klosterrunde' }
};

// Helfer: liefert lokalen GPX-Pfad (relativ zum App-Root) oder null
function findeGpxDateinameLokal(typ, gruppe, idx) {
  var key = typ + ':' + gruppe + ':' + idx;
  var m = GPX_MAPPING[key];
  return m ? ('gpx/' + m.dateiname) : null;
}
